### ISSUE TITLE
Impossible to start since the updated version to s6 overlay 3.0

### ISSUE THREAD

**Issue by SirOch27** [abesnier/docker-guacamole#1]
**Describe The Bug:**
Since the update of the 2022-01-20  (updated to s6 overlay 3.0), the docker doesn't want to start (see message log)

**To Reproduce:**
Install the docker image and try to launch it

**Expected behavior:**
launching the docker without issue

**Logs:**
Start container abesnier-guacamole failed: {"message":"OCI runtime create failed: container_linux.go:367: starting container process caused: exec: \"/init\": stat /init: no such file or directory: unknown"}.

```
Remove any sensative information.
```

**Screenshots:**

**Environment:**

* **Guacamole Version**: 
* **Operating System**:

**Comment by abesnier** [comment]
Thanks for the report. Image reverted to s6 overlay 2.2.0.2.
Further investigations ongoing.

**Comment by SirOch27** [comment]
Thank you for the fast action.
moreover there is a Tomcat error on the reverted image now
![image](https://user-images.githubusercontent.com/83179125/150944602-35048a16-5437-43fe-ab84-e2d905fb8469.png)

**Comment by abesnier** [comment]
Yeah, upgrading to s6_overlay v3 is much more work than expected (especially with some bugs that make things even more difficult...)
I am working on fixing it, but this may not be so soon...

**Comment by abesnier** [comment]
@SirOch27 I think it is fixed, with the support of the s6overlay team.
May I please ask you to try the image abesnier/guacamole:1.4.0-s6test?

**Comment by SirOch27** [comment]
@abesnier 
just tested the test image and all seems working now.
Docker launched well, connection are OK and 2FA works also.
happy to have helped you ;-)

**Comment by abesnier** [comment]
Nice!
There is a confirmed bug with s6 3.0 (not linked to my failed image, that was my mistake, but trying to fix it revealed a bug).
The image is currently built with s6 overlay binaries built by me. 
For consistency, I will update the guacamole:1.4.0-latest image when the fixed binaries are officially available (and update to Tomcat 9.0.58 at the same time).

**Comment by SirOch27** [comment]
Good news.
I am still using and testing version 1.4.0-s6_v3.
The only error i saw in the logs is this one with RDP connection:

 [http-nio-8080-exec-5] INFO  o.a.g.t.h.RestrictedGuacamoleHTTPTunnelServlet - Using HTTP tunnel (not WebSocket). Performance may be sub-optimal

But i had it on all the Onzu forks version.

**Comment by abesnier** [comment]
Yes, for what I've seen about this error, it is linked to proxy/reverse proxy configuration.
You may get better help in the [mailing list](https://lists.apache.org/list?user@guacamole.apache.org). Have a look at [this thread](https://lists.apache.org/thread/vsdqr7jnkqk5l4h5hz27y5cqof9d1nf8) for example.

**Comment by SirOch27** [comment]
Found the error: forgoten the Websocket configuration in the Synology reverse proxy.
All is working fine now :-)
