### ISSUE TITLE
Which image/tag is this hash ?

### ISSUE THREAD

**Issue by Zixim** [abesnier/docker-guacamole#18]
I created a container on 2023-05-23 10:47:09, using `image: abesnier/guacamole` in the compose file.  
The downloaded image has this hash : `abesnier/guacamole@sha256:2fbf45e5cc56ff4efd25bd72422c135a90cf57b689a2a97ecb896d75af6f158c`.  

Could you let me know which tags this was ? I'm thinking `1.5.0` but the hashes don't seem to match.
I'd like to be 100% certain about the versions before attempting an upgrade.

Thank you very much.

**Comment by abesnier** [comment]
If you pulled it on the 25th of May, that would be Guacamole 1.5.1, with Tomcat 9.0.75, S6 Overlay 3.1.5.0, and PostgreSQL JDBC 42.6.0.

If you did not specify a particular tag, you would have pulled the `latest` tag, which comes with a PostgreSQL 13 backend.

Unfortunately, I do not keep track of all the hashes of the images I build. 

But you can run `docker image inspect abesnier/guacamole`. That will provide you with a lot of details on the image, especially the environment variables. those will contain all the versions numbers of the image components. Example of the current `abesnier/guacamole:latest` image:

<pre>
            "Env": [
                "PATH=/usr/lib/postgresql/13/bin:/usr/local/tomcat/bin:/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "JAVA_HOME=/opt/java/openjdk",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8",
                "JAVA_VERSION=jdk-11.0.19+7",
                "CATALINA_HOME=/usr/local/tomcat",
                "TOMCAT_NATIVE_LIBDIR=/usr/local/tomcat/native-jni-lib",
                "LD_LIBRARY_PATH=/usr/local/tomcat/native-jni-lib",
                "GPG_KEYS=48F8E69F6390C9F25CFEDCD268248959359E722B A9C5DF4D22E99998D9875A5110C01C5A2F6059E7 DCFD35E0BF8CA7344752DE8B6FB21E8933C60243",
                "TOMCAT_MAJOR=9",
                <b>"TOMCAT_VERSION=9.0.76", </b>
                "TOMCAT_SHA512=028163cbe15367f0ab60e086b0ebc8d774e62d126d82ae9152f863d4680e280b11c9503e3b51ee7089ca9bea1bfa5b535b244a727a3021e5fa72dd7e9569af9a",
                "GUACAMOLE_HOME=/config/guacamole",
                "PGDATA=/config/postgres",
                "POSTGRES_USER=guacamole",
                "POSTGRES_DB=guacamole_db",
                <b>"S6OVERLAY_VER=3.1.5.0",</b>
                <b>"POSTGREJDBC_VER=42.6.0",</b>
                "GUAC_DOWN_PATH=https://dlcdn.apache.org/guacamole",
                <b>"GUAC_VER=1.5.2",</b>
                "GUAC_VER_PATH=1.5.2",
               <b> "PG_MAJOR=13",</b>
                "GUACD_LOG_LEVEL=info",
                "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
</pre>

I still have question on what you want to do. Versions bumps of Guacamole, Tomcat, S6 overlay and PostgreSQL JDBC can be done in place (i.e. as long as you use the same image tag, update will be transparent for you).

The only time you need to pay very particular attention for an upgrade is when you want to move from PostgreSQL 13 (the default one) to PostgreSQL 14 or 15 (images tags ending with `-pg14` or `-pg15`).

**Comment by Zixim** [comment]
Thanks for the elaborate info.

"_I still have question on what you want to do. Versions bumps of Guacamole, Tomcat, S6 overlay and PostgreSQL JDBC can be done in place (i.e. as long as you use the same image tag, update will be transparent for you)._"  
Well, yesterday I stopped the container, deleted the image, and restarted the container - causing `latest` to be pulled. The container failed to start properly. I then wanted to pull the previous version, and realised that I had no clue of what version was working for me.  Restored the docker host from backup, and Guacamole is now back, on the "old" version.  

So, now I'm just looking for all info on how to upgrade, without risking troubles.

If I understand you correctly, `latest` should still be PostgreSQL 13, so that wasn't the reason for my botched upgrade.
Will try  again, and will start another issue with log messages in case it goes bad once more.

**Comment by Zixim** [comment]
resolved in #19
