### ISSUE TITLE
Will stop connecting to Host needs a conatiner reboot 

### ISSUE THREAD

**Issue by celproject** [abesnier/docker-guacamole#24]
Will stop connecting to the host gets fixed after a reboot

**Comment by abesnier** [comment]
Yeah, sorry, I'm gonna need a bit more details...
Image, host OS, type of connection (SSH, RDP?), extract from the logs, etc...

**Comment by celproject** [comment]
Hi sorry 

Host is Debian 12  6.1 Kernel 
Image is latest had the issue with the previous version, So I re deployed yesterday 
Windows 10 ltsc rdp 
[logs guac.txt](https://github.com/abesnier/docker-guacamole/files/12608691/logs.guac.txt)
