### ISSUE TITLE
Unable to to VNC into itself on MacOS

### ISSUE THREAD

**Issue by mikecebul** [abesnier/docker-guacamole#27]
I installed this image on a m2 Mac Mini. I got it running with no issues. My goal is to access the mac away from outside the network. Plus a little benefit of having a container to connect to other machines. I setup a Cloudflare Tunnel to access the mac on port 8080. I can access guacamole with no issues. But I cant get guacamole to connect to the host computer (the Mac) through vnc. I set up the mac settings to allow VNC connections and tested with a vnc client, again no issues. But I can not get a VNC connection to the Mac Mini from the Guacamole server that is running on it. I'm starting to lose my mind trying different things and I could really use some guidance. I put in the local IP (192.168.1.103), or 127.0.0.1, or localhost, with port 5900. I've tried adding  user credentials, I've tried not using a name and only the VNC password, and every other combination you can think of. It's as if the docker container is unable to talk to the local network. I found this closed issue (https://github.com/abesnier/docker-guacamole/issues/22) but am unsure how it applies to my situation. I can't find any useful info in the logs, it just times out every time. Please someone help me.

**Comment by abesnier** [comment]
Hi, 

Indeed, issue 22 was more on how to retrieve the correct IP of the users.

Regarding your issue, does the connection to VNC works locally ? ie from your Guacamole client to your VNC server?

I have had issues to make VNC work (on Debian), but that was an issue with my VNC server and not Guacamole.
