### ISSUE TITLE
/init: 37: exec: s6-overlay-suexec: Exec format error

### ISSUE THREAD

**Issue by chunckky** [abesnier/docker-guacamole#4]
**Describe The Bug:**

Hi, on a odroid (arm64), when i want to start the image, I have this error :
/init: 37: exec: s6-overlay-suexec: Exec format error.

**To Reproduce:**

docker-compose up -d
with this docker-compose.yml
version: '3.7'
services:
  telem:
    image: abesnier/guacamole
    volumes:
      - type: bind
        source: /.../config
        target: /config
    ports:
      - 8080:8080/tcp
    networks:
      guacnet:
        ipv4_address: ...
networks:
  guacnet:
    ipam:
      driver: default
      config:
        - subnet: ...

**Expected behavior:**

The image start on ARM64.

**Logs:**
/init: 37: exec: s6-overlay-suexec: Exec format error
```
Remove any sensative information.
```

**Screenshots:**

**Environment:**
odroit n2+
CPU : arm64

docker engine : 20.10.13
api version : 1.41
containerd : 1.5.10
runc : 1.0.3
docker-init : 0.19.0
docker-compose : 1.25.0
docker-py : 4.1.0
cpython : 3.8.10

* **Guacamole Version**: 
latest
* **Operating System**: 
* ubuntu : 20.04

**Comment by mladecki** [comment]
Same issue on Raspi 4. Seems there is no build for this architecture. Issue inherits from oznu/guacamole.

**Comment by abesnier** [comment]
Hi, 

Sorry to see that, I think I messed up the S6 overlay install on the arm64 image.
I tried to build a new one, may I please ask you to try it: docker pull abesnier/guacamole:1.4.0arm64

**Comment by abesnier** [comment]
Great, so the issue was what I thought.

I'll modify my build process, and the guacamole:1.4.0 image should be fine for arm64 and amd64.

**Comment by abesnier** [comment]
Ok, build process is updated, @mladecki  @chunckky could you try the updated guacamole:1.4.0 or guacamole:latest?

I took the opportunity to update to Tomcat 9.0.60 also.

**Comment by mladecki** [comment]
@abesnier Thank you for your work. Running fine now.

**Comment by abesnier** [comment]
Glad to hear that!
Issue closed then.
