### ISSUE TITLE
Change /dev/log location?

### ISSUE THREAD

**Issue by alexbelgium** [abesnier/docker-guacamole#5]
**Describe Your Problem:**

Thanks for continuing to update and support this app. I'm trying to build an addon for [homeassistant](https://www.home-assistant.io/) based on your app, however I have encountered an issue.

HA os (home assistant os) doesn't allow to access /dev/log. This causes the issue "unable to bind socket to /dev/log: Read-only file system"

What could I change to make the logs use another location ? 

Here is my repo if you want : https://github.com/alexbelgium/hassio-addons-test/tree/master/guacamole
I've simply modified it to use /data instead of /config (as this is the only remanent location allowed in HA) ; and added a few scripts to provide a banner at launch.

Thanks,
Best regards

**Logs:**

```
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service syslogd-prepare: starting
s6-rc: info: service syslogd-prepare successfully started
s6-rc: info: service syslogd-log: starting
s6-rc: info: service syslogd-log successfully started
s6-rc: info: service syslogd: starting
s6-socklog: fatal: unable to bind socket to /dev/log: Read-only file system
```

**Screenshots:**

**Environment:**

* **Guacamole Version**: latest image from dockerhub
* **Operating System**: Home assistant OS built using Buildroot (https://github.com/home-assistant/operating-system#:~:text=Home%20Assistant%20Operating%20System%20is,optimized%20to%20run%20Home%20Assistant)

**Comment by abesnier** [comment]
To be honest, I have absolutely no idea!
But let me setup a test environment, and I'll see what I can do, looks like a good opportunity to teach me something new!

**Comment by alexbelgium** [comment]
Thanks very much :-) I'm also trying on my side.

I've tried a search & replace that didn't work : 
- ```find / -name *syslog* -type f | xargs grep "/dev/log"``` provides several matches
- but if I try to modify it with sed it fails to start with message : 
```s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out```

Guess it's not that simple :-) But I'm really not an expert here :-) Any input you will have will be very much welcome !

**Comment by alexbelgium** [comment]
Hi, thanks for the feedback and the effort in setting the test env ! Hope you are feeling better. No urgency, indeed I tried also but s6 seems extremely complicated to learn and get onboard

**Comment by alexbelgium** [comment]
I've found another way to make it work, so I'll close this issue. Thanks very much for your efforts.

**Comment by abesnier** [comment]
hi @alexbelgium. Sorry I could not help you.
Do you mind describing what you did, for future reference (and implementation in the image maybe?)

**Comment by abesnier** [comment]
No worries.
With all the issues I had with this version 3 of S6 overlay, I knew I should have quit and stayed with version 2!
Glad to know you found an image that works, and good luck with your project!
