### ISSUE TITLE
Doc improvement request

### ISSUE THREAD

**Issue by vincemulhollon** [abesnier/docker-guacamole#7]
Thanks for creating/maintaining this docker container its super appreciated by many people and works very well.

**Describe The Bug:**

Ideally, the readme and dockerhub docs should explain how to work around the default font "monospace" having a problem rendering underscores.

**To Reproduce:**

Open a SSH session with "Display" "Font name:" monospace or leave the font name blank and you'll get the default font which I believe is compiled into guacd source code as monospace but I could be wrong...

Simply type anything in the console with an underscore like whatever_whatever and the underscore will not visually render although it is there.

Change the default font to something nice like NotoSansMono and underscores are visible again.

**Expected behavior:**

This probably needs some rephrasing and general improvement, but add doc lines similar to:

There is an issue at this time displaying underscores in SSH sessions using the default font named "monospace".

If you change the Font name: option in a connection to a different font name, perhaps NotoSansMono then underscores will display properly.

If you would like a list of all fonts in the container, simply connect to the container shell and run "fc-list" which will list the eighty fonts available in the container.

**Logs:**

```
Remove any sensative information.
```

**Screenshots:**

Really the best screenshot and description is your own ticket at

https://issues.apache.org/jira/browse/GUACAMOLE-1478

**Environment:**

* **Guacamole Version**: 
* **Operating System**:

**Comment by abesnier** [comment]
Hi Vince, 

First of, thanks for your kind message at the top! This is far from the most popular Oznu'z fork, but seing that it reached almost 2K pulls, and that people actually appreciate it, it feels real good, man!

Second, you're right. This is an issue I have myself (see this [issue](https://issues.apache.org/jira/browse/GUACAMOLE-1478?jql=project%20%3D%20GUACAMOLE%20AND%20text%20~%20underscore)), so having a section in the readme is a good idea. I'll work on it this week.

Cheers
