### ISSUE TITLE
Watchtover | Could not do a head request for...

### ISSUE THREAD

**Issue by tordenflesk** [abesnier/docker-guacamole#8]
Could not do a head request for "abesnier/guacamole:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"

Related issue: https://github.com/containrrr/watchtower/issues/1528

**Comment by abesnier** [comment]
Thanks for bringing this to my attention. I was not aware at all about this issue.
I am building a test image, will run some tests, and will post when I deem the image fixed.

**Comment by abesnier** [comment]
I have republished the images with the proper flag (as mentionned in the sources i could find about this issue). @tordenflesk Can you please confirm if that fixes the issue? If not, I'll keep digging. Cheers.

**Comment by abesnier** [comment]
Not heard back, I guess I can close.
