### ISSUE TITLE
could not get it to start - database issue?

### ISSUE THREAD

**Issue by n3gwg** [abesnier/docker-guacamole#9]
docker volume create guacamole_config;
docker run --detach --name guacamole --restart=always --publish 8080:8080 --volume guacamole_config:/config abesnier/guacamole:latest-bullseye;

Continually presented database errors when a docker log guacamole command was executed.

**Comment by abesnier** [comment]
Hi. Can you post the logs please?
Is it a first run, or an upgrade or an update?
Was the directory guacamole_config empty?
Can you check this paragraph in the documentation: https://github.com/abesnier/docker-guacamole#the-container-fails-to-start-properly
Can you try to either run with the user root (docker run -u root), or mount the colume in read/write ( --volume guacamole_config:/config:rw)

Cheers

**Comment by abesnier** [comment]
Hi. 
Having not heard back from you, I will assume the issue is either fixed or you switched to another image.
